/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.common {
    export class commonWaitingNodeUI extends Laya.View {
		public ani1:Laya.FrameAnimation;
		public box1:Laya.Box;
		public box2:Laya.Box;
		public box3:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("common/commonWaitingNode");
        }
    }
    REG("ui.common.commonWaitingNodeUI",commonWaitingNodeUI);
}
export module ui.loading {
    export class LoadingUI extends Laya.View {
		public img_bg:Laya.Image;
		public progressLoading:Laya.ProgressBar;
		public textLoading:Laya.Label;
		public textLoadingNum:Laya.Label;
		public banhao:Laya.Box;
		public label_version:Laya.Label;
		public log_test:Laya.Label;
		public state_text:Laya.Label;
		public btn_reset:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("loading/Loading");
        }
    }
    REG("ui.loading.LoadingUI",LoadingUI);
}